/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  'auth/login': {
    /** Login */
    post: operations['postauth-login'];
  };
  '/guest/{guestId}': {
    /** Guest */
    get: operations['get-guest'];
    parameters: {
      path: {
        /** @description the Guest's id */
        guestId: string;
      };
    };
  };
  '/reservation/{reservationId}': {
    /** Reservation */
    get: operations['get-reservation'];
    parameters: {
      path: {
        /** @description The reservationId */
        reservationId: string;
      };
    };
  };
  '/reservations/{fromDate}/{toDate}': {
    /** Reservations */
    get: operations['get-reservations'];
    parameters: {
      path: {
        /** @description ISO Date */
        fromDate: string;
        /** @description ISO Date */
        toDate: string;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** User */
    User: {
      /** @description Unique identifier for the given user. */
      id: number;
      firstName: string;
      lastName: string;
      /** Format: email */
      email: string;
      /**
       * Format: date
       * @example 1997-10-31
       */
      dateOfBirth?: string;
      /** @description Set to true if the user's email has been verified. */
      emailVerified: boolean;
      /**
       * Format: date
       * @description The date that the user was created.
       */
      createDate?: string;
    };
    /** Email */
    Email: {
      id?: string;
    };
    /**
     * Email
     * @description The Email entity is included with the Guest entity and allows for one or more email related to the guest to be sent.
     */
    Email_2: {
      /**
       * @description Indicates if the email address is business, personal or other. The code values are specified by the hotel.
       *
       * This field will vary from hotel to hotel based on the programs they accept making this field a hotel enumeration.
       * @example Personal
       */
      email_type?: string;
      /** @description This flag indicates whether this is the guests preferred email address for communications. */
      email_is_primary?: boolean;
      /**
       * @description An email address associated with the guest.
       * @example john.smith@provider.com
       */
      email_address: string;
    };
    /**
     * Guest
     * @description The Guest entity is used within the Reservation entity to specify information about the guests related to the reservation. There are two instances of the Guest entity in the Reservation, one for the primary guest and an array for additional guests
     */
    Guest: {
      /**
       * @description Holds various name suffixes and letters (e.g. Jr., Sr., III, Ret., Esq., MD, PhD).
       * @example Jr.
       */
      name_suffix?: string;
      /**
       * @description Salutation of honorific (e.g. Mr., Mrs., Ms., Miss, Dr.).
       * @example Mr.
       */
      name_prefix?: string;
      /**
       * @description Given name, first name or names.
       * @example John
       */
      name_first?: string;
      /**
       * @description The middle name or initial of the person name.
       * @example Michael
       */
      name_middle?: string;
      /**
       * @description Family name, last name. This is the only required field for name, and hence any variations on the standard name would be here. For instance if a guest is only a single named guest (i.e. Madonna) it would go into this field. The same for aliases that are a single name.
       * @example Smith
       */
      name_last: string;
      /**
       * @description A category applied to the guest that is aligned with the level of services that they recieve during their stay. This is typically aligned to the "level of importance" that a guest holds for the hotel or the brand, and is assigned on a contextual basis.
       *
       * This field is very stay specific, and has to do with why you are at the hotel at this time. For instance, an event planned may be a certain VIP Code during an event, and a different VIP code or no VIP code when staying for leisure. Also the VIP code is not consistent across a brand. A guest could be a VIP in one hotel and not another.
       *
       * There is no direct relationship between vip code and rate code, though both can impact service level. For more sophisticated business rules multiple attributes can determine service level (VIP Code, Rate Code, Room Rate, Group Code, etc)
       * @example VIP1
       */
      vip_code?: string;
      /**
       * @description Unlike the company name in the Reservation, this is a string field provided by the guest. This is not a specific entity in the PMS and therefore does not drive rates. The company at the reservation could be different from the company at the guest level, for this reason, the reservation company drives rate details and the guest company name is more informational. This field is not typically required.
       * @example IBM
       */
      company_name?: string;
      /**
       * @description ISO 639-1 - The language that the guest prefers to communicate in.  The language may not be supported by the hotel. If the hotel supports this language it may be used to communicate with the guest while on property.
       * @example  en
       */
      prefered_language?: string;
      /**
       * @description Unique ID within the database instance for the guest profile. Issued by the PMS. This is different from the loyalty ID for the guest that is unique across the brand.
       * @example 789125
       */
      profile_id: string;
      loyalty?: components['schemas']['Loyalty'];
      /**
       * @description This is an SMS enabled phone number that is capable of receiving text messages.
       *
       * **We acknowledge in the current world there are opt in, opt out compliance issues; they will not be handled in this specification.
       * @example 312-555-1212
       */
      phone_mobile?: string;
      email?: components['schemas']['Email_2'];
      /**
       * @description A set of codes that represent desired options for a given guest. This list serves as instructions for various departments in things like room selection, service delivery, and charge routing etc. These are preferences that the guest adds or requests to be added to their profile to be utilized across stays.The preferences are codes that to the staff represent options such as King Bed, Non-smoking Room, High Floor, Extra bed, Birthday, ADA, VIP. It is possible that there could be preferences that are in conflict with each other.
       *
       * Generally there are preferences at the profile level as well as the reservation level. The preferences on the profile level may be applied at the reservation level, but the reservation level preferences are specific to that particular stay. Guest preference may influence the reservation preferences; however, reservation preferences may override the guest preferences as a guest may have specific needs for that stay.
       *
       * Example: K1,NS,HF
       */
      preferences: readonly string[];
    };
    /**
     * Loyalty
     * @description The Loyalty entity is included within the Guest entity and allows data for one or more loyalty programs related to the guest to be sent.
     */
    Loyalty: {
      /**
       * @description This field represents a loyalty program that the guest and the hotel are associated with. Typical loyalty programs may include hotel , airline, car rental or other programs.
       *
       * This field will vary from hotel to hotel based on the programs they accept making this field a hotel enumeration.
       * @example BA
       */
      loyalty_program_type: string;
      /**
       * @description Tier is dependent on the loyalty program and the level that they support. We may not know the level for all programs, but it will typically be sent with hotel loyalty information.
       *
       * This field will vary from hotel to hotel based on the programs they accept making this field a hotel enumeration.
       * @example GOLD
       */
      loyalty_level?: string;
      /**
       * @description This is the unique identifier issued by the loyalty company to identify the loyalty member.
       * @example G1234567X
       */
      loyalty_membership_id: string;
    };
    /**
     * Property
     * @description The Property entity is contained within the Reservation entity and is used to identify the hotel.
     */
    Property: {
      /**
       * @description A unique identifier for a hotel, that is unique within the chain if it belongs to a chain.
       * @example ORDEC
       */
      property_code: string;
      /**
       * @description A unique identfier for the parent company, e.g. Hyatt, Marriott, Hilton, etc.  Chain code is optional for the case where a hotel is an independent and not affiliated with a chain.
       * @example IHG
       */
      chain_code?: string;
    };
    /**
     * Reservation
     * @description The Reservation entity includes a limited set of data fields, those that support a wide variety of use cases for vendor products that integrate with property management systems. The Reservation entity does not and is not intended to include a full set of reservation elements but just those needed to support the express model.
     */
    readonly Reservation: {
      readonly primary_guest: components['schemas']['Guest'];
      readonly additional_guests?: readonly components['schemas']['Guest'][];
      readonly property: components['schemas']['Property'];
      /**
       * Format: date-time
       * @description ISO 8601 Format - The date that the guest is arriving and the stay begins. This field contains time but may just be a date that is sent.
       * @example 2022-09-15
       */
      readonly arrival_date: string;
      /**
       * Format: date-time
       * @description ISO 8601 Format - The date that the guest is departing and the stay ends. This field contains time but may just be a date that is sent.
       * @example 2022-09-17
       */
      readonly departure_date: string;
      /**
       * Format: date-time
       * @description ISO 8601 Format - Aka ETA. Estimate of arrival provided by the guest.
       * @example 2022-09-15T17:30:00+00:00.000Z
       */
      readonly arrival_estimated_time?: string;
      /**
       * Format: date-time
       * @description ISO 8601 Format - Aka ETD. Guest supplied estimate of departure.
       * @example 2022-09-17T07:30:00+00:00.000Z
       */
      readonly departure_estimated_time?: string;
      /**
       * @description Count of adults on the reservation. The number reflected here is a snapshot of what is current. This may change throughout the stay as additional guests arrive/depart within a resvation.
       * @example 2
       */
      readonly number_of_adults?: number;
      /**
       * @description Count of children on the reservation. The number reflected here is a snapshot of what is current. This may change throughout the stay as additional guests arrive/depart within a resvation.
       *
       * @example 3
       */
      readonly number_of_children?: number;
      /**
       * @description A code that describes the "kind" of room, which is the specific product being sold to the guest. This groups rooms based on configuration, size, view, and other important booking or operational attributes. (i.e King, Suite, Double Double, Beach King).
       *
       * This is used by both the booking system to know how to price the room as well as by operations such as housekeeping to know how to service the room.
       *
       * The Room Type is configured at every hotel to segment their inventory and provide differentiation in pricing. This helps hotels track what is available in the inventory for any type.
       *
       * This field is a Hotel Enumeration and the available room types are unique per hotel.
       * @example KOCV
       */
      readonly room_type_code: string;
      /**
       * @description A human readable name of the room that is friendly for consumers. This is here for convenience, the Room Type Code can be used for programmatic cases.
       * @example King Suite Beachside
       */
      readonly room_type_name?: string;
      /**
       * @description The number or name of the room the guest is staying in. This could be a virtual room (combining multiple rooms). When a reservation is made, rooms are typically not assigned until check-in or pre-check-in. When a room gets assigned depends on the property SOPs.
       *
       * Since the Room is not known until later in the life cycle of the Reservation, once it is assigned it may cause other changes in the reservation. The Room drives a lot of other Reservation fields such as the Room Type, Rate, etc. If a guest gets assigned a Room that is not of the same Room Type as was booked, the Room Type will be updated to reflect the one that the guest is staying in. Other fields such as Rate may also be updated.
       * @example 00123B (Hotel Enum)
       */
      readonly room_number?: string;
      /**
       * @description This refers to the company that is linked to the reservation as an entity and is typically credited with generating this reservation. This company is not necessarily the organization the guest works for. It could be a travel agent, wedding organizer, bus tour organizer etc.
       *
       * In the case of the business traveler, the idea of a company is not always straightforward. For instance Brian may be an employee at Apigee, a wholly owned subsidiary of Google, going to a conference on behalf of HTNG. This field now has 3 potential companies, all of which are valid in different contexts. The value of the field is decided by the individual making the booking and there is not a consistent approach between hotels.
       *
       * The name is not expected to be unique. For instance there could be many reservations that return the "IBM" company, and that may not actually be the same company. Behind the scenes the company has a unique ID which is used to link the reservation. That ID is not accessible in this particular spec, as we do not think it is relevant for our use cases.
       * @example IBM
       */
      readonly company_name?: string;
      /**
       * @description The state of the world according to the PMS about this particular reservation in it's Booking lifecycle. This is automatically set in the PMS based on where the guest is in their journey. Sample statuses are Booked, Arriving, In-House, Departed, No-Show, Canceled etc.
       *
       * The statuses very by PMS system and as such this field is defined as a PMS Enumeration.
       * @example Reserved
       */
      readonly reservation_status_pms: string;
      /**
       * @description A standard set of statuses that aligns all the different Reservation Status nomenclature in  various PMS systems. Since the ideas of a status is the same, this applies a common naming structure, mapping per PMS.
       *
       * This field is defined as an HTNG Enumeration.
       * @example PreConfirmed
       * @enum {string}
       */
      readonly reservation_status_htng: 'Reserved' | 'NoShow' | 'PreCheckedIn' | 'InHouse' | 'CheckedOut' | 'Canceled' | 'PreConfirmed';
      /**
       * @description A unique identifier for a specific negotiated sale that identifies a set of guests coming to the hotel for a meeting or event. This Group Code is created when a hotel sales department executes a contract for a block of rooms at a specific time, for a specific price. Groups typically negotiate rates and other details and hence the terms for the group and the rates will be very specific. The group code links all the reservations that relate to this specific sale and specific contract.
       * @example IBMA
       */
      readonly group_code?: string;
      /**
       * @description  A unique identifier for a reservation within an instance of the PMS in a given property. This is the primary ID for any API calls. This is meant to be unique across time (unlike some confirmation numbers).
       * @example 2312543
       */
      readonly pms_reservation_id: string;
      /**
       * @description A set of unique Reservation IDs that this reservation is shared with. When there are multiple reservations for a given room its important for systems like key locks to understand both reservations are sharing the same room so that the generated keys do not lock each other out. This allows multiple reservations to be in the same room in such cases as multiple people sharing the same room for a conference. It is useful for having separate folios, different stay dates. If none of these apply, the PMS would just have multiple guests in a single room. For in house reservation this information may also be deduced by the reservation start end date and room number overlapping the reservation. However on a pre arrival reservation there is no way to indicate that two reservations will be staying together except by this method.
       *
       * Example:  2156,2157,2158
       */
      readonly pms_reservation_id_share_with?: readonly string[];
      /**
       * @description An alphanumeric code issued by the PMS that is unique at the time of issuance across all active reservations. This is intended to be a human readable code used to find a reservation in kiosks, apps, calls, etc.
       * @example AC1X543
       */
      readonly pms_confirmation_code: string;
      /**
       * @description Similar to a pms_confirmation_id, this would be the human readable ID that is issued by a system outside the PMS. There external systems could be CRS (Central Reservation System), OTA (On-line travel agent), GDS (Global Distribution System), RMH (Revenue Management System). The guest will have a confirmation number based on where the reservation is booked. If a guest books on an OTA it may be an Expedia confirmation, if they book on a hotel website it may be the CRS confirmation.
       *
       * Example:  Expedia:112DHSG,Sabre:KDJDJ21
       */
      readonly external_confirmation_code?: readonly string[];
      /**
       * @description A set of codes that represent desired options for a given stay. This list serves as instructions for various departments in things like room selection, service delivery, and charge routing etc. These options are aggregated at the reservation level from various sources (Reservation booking, VIP code, guest profile, group profile, and rate plan). The preferences are codes that to the staff represent options such as King Bed, Non-smoking Room, High Floor, Extra bed, Birthday, ADA, VIP.
       *
       * Example:  K1,NS,HF
       */
      readonly reservation_preference_code?: readonly string[];
      /**
       * @description ISO 4217 Format - This is the currency code that corresponds to the rate_plan_code and room_rate fields. It should be the same as the base currency that hotel operates in but it could be a different currency if the hotel and the PMS support multi-currency functionality.
       * @example USD
       */
      readonly currency_code: string;
      /** @description Indicates whether this folio allows charges, typically as a result of a CC on file.  This includes charges from other systems (outside of the PMS) related to outlets such as a gift shop, restaurant, spa, etc. */
      readonly is_posting_allowed: boolean;
      /** @description An array of room_rate objects which allows for the rates for all days of the reservation to be sent.  The start_date and end_date may be used to send the rate for a range of dates, or the rate may be sent for each individual day of the stay. */
      readonly room_rate_info: components['schemas']['RoomRate'][];
    };
    /**
     * RoomRate
     * @description ISO 8601 Format - The Room Rate entity includes data fields that affects the room rate. This entity is an array so that rates for the entire stay can be sent.
     */
    RoomRate: {
      /**
       * @description ISO 8601 Format - The date that this room rate stops (this is an exclusive date similar to a check out date).   The difference between the start date and the end date can be utilzed to determin how long this rate is effective.  The end date is speaking to a night rate, if the start date and the end date are the same it is assumed it is a day rate.  Since the end date is exclusive, when the start date and the end date are the same then this represents a day rate.
       * @example 2022-09-17
       */
      end_date: string;
      /**
       * @description Count of adults on the reservation. The number reflected here is a snapshot of what is current. This may change throughout the stay as additional guests arrive/depart within a reservation.
       * @example 2
       */
      number_of_adults?: number;
      /**
       * @description Count of children on the reservation. The number reflected here is a snapshot of what is current. This may change throughout the stay as additional guests arrive/depart within a reservation.
       * @example 2
       */
      number_of_children?: number;
      /**
       * @description A code that represents the rate structure under which the reservation is being booked. This rate structure is an umbrella that when combined with other aspects of the reservation (Date, room type, package, group code) will set the price for the room for each given night and impact the type of amenities/service the guest receives (Tier of internet, meal included, housekeeping service).
       *
       * The acceptable values will vary from hotel to hotel making this field a hotel enumeration.
       * @example BAR
       */
      rate_plan_code: string;
      /**
       * @description The rate plan name is a human readable version of the rate_plan_code. For example, a hotel may sell a rate plan code of "BAR" which may have a rate plan name of "Best Available Rate."
       * @example Best Available Rate
       */
      rate_plan_name?: string;
      /**
       * @description The amount charged for the accommodation is based on the rate_plan_code and room_type. This is typically a day, but does not have to be. This field will roll the rate up into a daily rate. This is the amount that will be posted to the guest's folio on a day by day basis. It should be the exact amount that was quoted to the guest at the time of booking. In some cases, this may include items like taxes (VAT) and packaging inclusions (breakfast), but in other cases it may not include these items.
       * @example 200.00
       */
      room_rate: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** Login */
  'postauth-login': {
    requestBody?: {
      content: {
        'application/json': {
          apiKey: string;
          apiName: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  /** Guest */
  'get-guest': {
    parameters: {
      path: {
        /** @description the Guest's id */
        guestId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['Guest'];
        };
      };
    };
  };
  /** Reservation */
  'get-reservation': {
    parameters: {
      path: {
        /** @description The reservationId */
        reservationId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['Reservation'];
        };
      };
    };
  };
  /** Reservations */
  'get-reservations': {
    parameters: {
      path: {
        /** @description ISO Date */
        fromDate: string;
        /** @description ISO Date */
        toDate: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['Reservation'][];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': external['htng-api.json'];
        };
      };
      529: {
        content: {
          'application/json': {
            errorType: string;
            code: string;
            message: string;
          };
        };
      };
    };
  };
}
