#!/bin/bash
CONTEXT=ohip.aiGuest
npx poly function add paymentEventsCache src/ai-gx/fxPaymentEventsCache.ts --context $CONTEXT --server --description "Read, create or update cached payment events. Events cached are deleted after 24 hrs." &&
npx poly function add paymentEventServerHandler src/ai-gx/fxPaymentEventHandler.ts --context $CONTEXT --server --description "Payment event handler. It receives an Adyen payment event and stores it in the payment events cache." &&
npx poly function add searchHotelsByLocation src/ai-gx/fxSearchHotelsByLocation.ts --context $CONTEXT --server --description "Search hotels by location. The hotelId's in the response should be used as input when calling other functions on this plugin" &&
npx poly function add searchHotelAvailability src/ai-gx/fxSearchHotelAvailability.ts --context $CONTEXT --server --description "Search hotel availability for any given current or future date. The hotelId provided as input should come from calling searchHotelsByLocation." &&
npx poly function add createResWithPayLink src/ai-gx/fxCreateResWithPayLink.ts --context $CONTEXT --server --description "Create a reservation using a payment link so personal details are not entered in chatgpt. The hotelId provided as input should come from calling searchHotelsByLocation." &&
npx poly function add checkInGuest src/ai-gx/fxCheckIn.ts --context $CONTEXT --server --description "Check in a guest using reservation confirmation number. Note that confirmation number must come from createResWithPayLink. The hotelId provided as input should come from calling searchHotelsByLocation" &&
npx poly function add getConciergeServices src/ai-gx/fxConciergeServices.ts --context $CONTEXT --server --description "Get all concierge services available such as Breakfast, Renting a bike, booking a taxi, or even booking attraction tickets like London Eye. The hotelId provided as input should come from calling searchHotelsByLocation" &&
npx poly function add requestConciergeService src/ai-gx/fxConciergeServices.ts  --context $CONTEXT --server --description "Request a concierge service from all available services. Use getConciergeServices to get all available services. The hotelId provided as input should come from calling searchHotelsByLocation" &&
npx poly function add checkBillCharges src/ai-gx/fxCheckBillCharges.ts --context $CONTEXT --server --description "Check the current bill for a given guest using a reservation confirmation number. The hotelId provided as input should come from calling searchHotelsByLocation." 