#!/bin/bash
CONTEXT=ohip.aiGuest

npx poly function add paymentEventsCache src/ai-gx/fxPaymentEventsCache.ts --context $CONTEXT --server --description "Create, read, or update cached payment events. Use this to temporarily store payment data received from Adyen. Cached events expire automatically after 24 hours." &&
npx poly function add paymentEventServerHandler src/ai-gx/fxPaymentEventHandler.ts --context $CONTEXT --server --description "Handle incoming Adyen payment notifications. Always store each received payment event in the payment events cache using paymentEventsCache." &&
npx poly function add searchHotelsByLocation src/ai-gx/fxSearchHotelsByLocation.ts --context $CONTEXT --server --description "Find hotels near a specific location or city. Use the returned hotelId values as inputs for any subsequent hotel-related functions." &&
npx poly function add searchHotelAvailability src/ai-gx/fxSearchHotelAvailability.ts --context $CONTEXT --server --description "Retrieve room availability for a given hotelId and date range. Always use hotelId values obtained from searchHotelsByLocation." &&
npx poly function add createResWithPayLink src/ai-gx/fxCreateResWithPayLink.ts --context $CONTEXT --server --description "Create a hotel reservation using a secure payment link so guest details stay private. The hotelId input must come from searchHotelsByLocation." &&
npx poly function add checkInGuest src/ai-gx/fxCheckIn.ts --context $CONTEXT --server --description "Check in a guest using their reservation confirmation number. Use the arrival date as the check-in date. Do not ask for a date if it's already known. The confirmation number must come from createResWithPayLink, and hotelId from searchHotelsByLocation." &&
npx poly function add getConciergeServices src/ai-gx/fxConciergeServices.ts --context $CONTEXT --server --description "List all concierge services available for a hotel (e.g., breakfast, taxi booking, bike rental, attraction tickets). The hotelId must come from searchHotelsByLocation." &&
npx poly function add requestConciergeService src/ai-gx/fxConciergeServices.ts --context $CONTEXT --server --description "Submit a concierge service request (e.g., breakfast, taxi, or activity). Always retrieve the list of available services first using getConciergeServices. Use hotelId from searchHotelsByLocation." &&
npx poly function add checkBillCharges src/ai-gx/fxCheckBillCharges.ts --context $CONTEXT --server --description "Retrieve the current bill and charges for a guest using their reservation confirmation number. Always use hotelId values obtained from searchHotelsByLocation." 